version: 0.2

phases:
  install:
    commands:
      - echo Skipping install phase, no setup required.

  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

  build:
    commands:
      - echo Building, Testing, and Packaging the application...
      - cd uperApp/uperApp   # Corrected path
      - mvn package

artifacts:
  files:
    - uperApp/uperApp/target/*.jar   # Correct artifact path

cache:
  paths:
    - '/root/.m2/**/*'  # Caching Maven dependencies
