version: 0.2

phases:
  install:
    commands:
      - mkdir -p uperapp
      - cd uperapp
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  build:
    commands:
      - echo Building, Testing and packaging the application...
      - if [ -f pom.xml ]; then echo "pom.xml file found"; else echo "pom.xml file not found"; fi
      - mvn package
  post_build:
    commands:
      - echo Build completed.

artifacts:
  files:
    - target/*.jar
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'