version: 0.2.0

working_directory: ./uperApp

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo Using pre-installed Maven...
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
  build:
    commands:
      - echo Building, Testing and packaging the application...
      - mvn clean package
  post_build:
    commands:
      - echo Build completed on `date`
      - ls -al
      - echo "Running tests"
artifacts:
  files:
    - target/*.jar
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'