version: 0.2

phases:
  install:
    commands:
      - echo Skipping install phase, no setup required.

  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

  build:
    commands:
      - echo Building, Testing, and Packaging the application...
      - cd uperApp/uperapp   # Navigate to the correct subdirectory
      - mvn package  # Now Maven can find the pom.xml

artifacts:
  files:
    - uperApp/uperapp/target/*.jar   # Ensure this path matches where your JAR is generated

cache:
  paths:
    - '/root/.m2/**/*'  # Caching Maven dependencies
